name: Audit Formula

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Audit Formula (strict)
        run: brew audit --strict Formula/archi2likec4.rb

      - name: Test Formula
        run: |
          brew install --build-from-source Formula/archi2likec4.rb
          brew test archi2likec4
